# Generated by Django 4.2.16 on 2024-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$AnSG4xYDw2EMtLIR9XhH3w$ABF+v5aGEct+mubKFfCm7k7I5sa9IbulwoxMN0VBhEc=', max_length=128),
        ),
    ]
