# Generated by Django 4.2.16 on 2024-11-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$AXPkVwBduqmCY7pJv7HP7w$1z6ZSXv4LFVPl3lg0v+Jf3w8Pe8oAJlW+7NHMvGTuR4=', max_length=128),
        ),
    ]
