# Generated by Django 5.1.1 on 2024-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$50EAenhIrMnoBBLh5u6ZdA$xr/tbH1/42J2EesIXEVnM3+UnrJHoqzW2g4BVF2jOnU=', max_length=128),
        ),
    ]
