# Generated by Django 5.1.1 on 2024-11-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$X6OIwBEjbjHC7OczOB0D72$0Kx+scS4CCCfLMz2Czbn9pd+KoDAN4v4/2E+I+4E5wU=', max_length=128),
        ),
    ]
